### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Ahmad-Ayyoub** [OpenLiberty/draft-guide-microprofile-opentracing#1]
In general it looks fine. However I have few things maybe we can adjust on.

- [x] Not sure about the title of the guide. Maybe:
Enabling distributed tracing in microservices. 
- [x] for abstract title:
MP OpenTracing should be Microprofile OpenTracing. 

What you will learn:
- [x] use one term MP OpenTracing or Microprofile OpenTracing ?
- [x] Note, that -> Note that or even remove that and just directly say The Micorprofile OpenTracing ..
- [x] I think you can combine the third and fourth paragraphs. Maybe like that:

MicroProfile OpenTracing aims to enable distributed tracing in microservices without having to add any explicit distributed tracing code to the application given an existing distributed tracing system. [adjust to that as you like]

- [x] The complete MicroProfile OpenTracing specification.. -> not sure if we should reference the spec. none of our guides mentioned that.

Getting started:

- [x]  For the purpose of this guide,  Zipkin is used as the distributed tracing system. Install it here[link].
Before you proceed, run Zipkin server and make sure it is up by accessing it at http://localhost:9411. 
[is that better?]

- [x] For us, Zipkin can be accessed at http://localhost:9411 -> For the purpose of this guide maybe .. ?

Try what you’ll build
- [x] too big -> when it gets rendered , guides-common links will take more space + long section for telling use what to do . Also not sure if u need the second guides-common link. 
- [ ]  inventory and services links are repeated. You can look at others or you can reference them somewhere at top and refer to them as `/inventory/system` and `/system/properties` endpoints
_I'd rather not do this because then links are no longer clickable_
- [x] `GET` 
- [x]  I suggest you move the services links with the explanation of why they should be on separate servers at maybe what you will learn learn section similar to other guides.

Running with Docker
- [x] then ignore the steps above and follow these instructions instead:  
 If you followed the steps above, first stop both Open Liberty server instances  -> it is kinda misdirecting first time i read. It is better to refer users to directly use Docker (or read this section) from the beginning somewhere at the top where you see fit. Then they can independently continue form here.  
_Made the Docker section into its own section above the build instructions. This seems to be more clearer._
- [ ] Links. Referencing them as mentioned above would be better. 
_I dont want to do this because then the guide become difficult to follow. Links are long and fit kind of awkwardly into the paragraphs, but I'd rather show the links than start explaining what each endpoint is._

Existing distributed tracing system
- [x]  not sure about this subtitle 
_Agreed. The title is also completely wrong. Changed to "Existing Tracer implementation"._
- [x] Complete installation instructions for this user feature are available in the IBM Knowledge Center.-> is this needed to make the app work? If so this is too much reading. Can you just briefly point the main things that is needed only?  
_The feature is installed automatically during the Maven build. But I see how it wasn't clear enough. I briefly clarified this part._

Enabling distributed tracing
- [x] This subsection has a repeated information:

Before you proceed, remember that you must have an existing distributed tracing system implemented in your environment to make use of MP OpenTracing.

I think you can move what is in "Existing distributed tracing system" section to here and remove that section ?

Enabling explicit distributed tracing code instrumentation
- [x]  annotation onto the list method to enable tracing with this method: -> annotation onto the list method to enable tracing. ?
- [x] also maybe `list()` not just `list`
- [x]  2 spans long, -> two spans long
- [x] images are too small and also too close from the texts. Is their a way maybe to frame them.
_I added extra margins around the images, but unfortunately I can't make them any bigger since they will be too big to fit into a page._

Injecting and customizing a Tracer
- [x] Then, use it to define a new child span in the list method around the for loop: -> 
why should i create a child span around the loop? what is the point? I do not understand
- [x]  image is not showing up

-----

- [x] mvn install on finish/start directories -> old tests fail (maybe remove them since you do not have test section and you do not need them @evelinec ) ?
_Old tests currently fail because the system service runs in a separate server and one of the tests depends on the service being up. The current maven build will start and stop the system service before the tests actually run. This is something I'm looking into right now, but I'm not sure its possible to go around this problem._

- [x] Great job.

**Comment by Kubik42** [comment]
done as of 4d7f3400bdcb5f2f7966bb351b5c7b3e8356e021

**Comment by Ahmad-Ayyoub** [comment]
- [ ] Also fix ur copy rights date 2017, 2018 for old files and 2018 for new ones
- [ ] fix indentations in pom.xml and any other files.

**Comment by Kubik42** [comment]
@Ahmad-Ayyoub can you close this? Mostly everything has been addressed.

**Comment by Ahmad-Ayyoub** [comment]
Oh sure.
